import React from 'react'
import { motion } from 'framer-motion'
import useWellnessStore from '../context/useWellnessStore'
import { getEmotion } from '../utils/emotions'
import { Calendar, Download, AlertCircle, ArrowLeft, FileText, TrendingUp } from 'lucide-react'

export default function MoodHistoryPage() {
  const goHome = useWellnessStore((s) => s.goHome)
  const moodHistory = useWellnessStore((s) => s.moodHistory)
  const safetyPlan = useWellnessStore((s) => s.safetyPlan)

  // Group history by date for a simplified view
  const last7Days = [...moodHistory].reverse().slice(0, 7)

  const handleExportForDoctor = () => {
    const today = new Date().toLocaleDateString()
    
    // Calculate some simple stats
    const totalEntries = moodHistory.length
    const moodCounts = moodHistory.reduce((acc, curr) => {
      acc[curr.emotionId] = (acc[curr.emotionId] || 0) + 1
      return acc
    }, {})

    let report = `=== Serenspace Professional Handover Report ===\n`
    report += `Generated on: ${today}\n\n`
    report += `This report summarizes private wellness trends to help facilitate a conversation with your healthcare professional.\n\n`
    
    report += `[SUMMARY OF TRENDS]\n`
    report += `Total mood entries logged: ${totalEntries}\n`
    Object.entries(moodCounts).forEach(([id, count]) => {
      report += `- Felt "${id}": ${count} times\n`
    })
    
    report += `\n[LATEST 5 ENTRIES]\n`
    moodHistory.slice(-5).reverse().forEach(entry => {
      report += `- ${entry.date}: ${entry.emotionId}\n`
    })

    report += `\n[SAFETY PLAN OVERVIEW]\n`
    report += `Warning Signs: ${safetyPlan.warningSigns || "None listed."}\n`
    report += `Coping Strategies: ${safetyPlan.copingStrategies || "None listed."}\n`
    report += `Internal Supports: ${safetyPlan.supporters || "None listed."}\n`

    report += `\n\nDISCLAIMER: This document was generated by a self-help tool. It is intended to support, not replace, clinical diagnosis.`

    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `serenspace-doctor-summary-${Date.now()}.txt`
    link.click()
    URL.revokeObjectURL(url)
  }

  return (
    <main className="flex flex-col items-center min-h-screen px-6 pt-24 pb-12 overflow-x-hidden">
      <motion.button
        onClick={goHome}
        className="absolute top-24 left-6 md:left-12 text-[var(--text-muted)] hover:text-[var(--text-main)] transition-colors text-sm flex items-center gap-1.5 z-30"
        initial={{ opacity: 0 }} animate={{ opacity: 1 }}
      >
        <ArrowLeft className="w-4 h-4" /> Back to Home
      </motion.button>

      <div className="w-full max-w-4xl flex flex-col gap-10">
        <div className="text-center md:text-left">
          <div className="flex items-center gap-3 mb-2 justify-center md:justify-start">
            <div className="p-2.5 bg-[var(--color-secondary)]/10 text-[var(--color-secondary)] rounded-xl">
              <TrendingUp className="w-5 h-5" />
            </div>
            <p className="text-xs font-bold tracking-[0.2em] uppercase text-[var(--color-secondary)]">Mood Reflection</p>
          </div>
          <h1 className="text-3xl md:text-4xl font-semibold text-[var(--text-main)]">Your Journey at a Glance.</h1>
          <p className="text-[var(--text-muted)] text-sm max-w-md mt-2">
            A private view of your emotional patterns. This data stays on your device and helps you see how you're healing.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Recent History Grid */}
          <div className="lg:col-span-2 glass-card p-6 border border-[var(--border-subtle)] space-y-6">
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4 text-[var(--text-muted)]" />
              <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-main)]">Recent Log</h3>
            </div>

            {moodHistory.length === 0 ? (
              <div className="py-12 text-center">
                <p className="text-sm text-[var(--text-muted)] italic">No entries yet. Your history will appear here as you use the space.</p>
              </div>
            ) : (
              <div className="space-y-3">
                {last7Days.map((entry, i) => {
                  const emotion = getEmotion(entry.emotionId)
                  return (
                    <div key={i} className="flex items-center justify-between p-4 bg-white/5 border border-white/5 rounded-xl hover:bg-white/10 transition-all">
                      <div className="flex items-center gap-4">
                        <span className="text-2xl">{emotion?.emoji || '❔'}</span>
                        <div>
                          <p className="text-sm font-semibold text-[var(--text-main)] capitalize">
                            Felt {entry.emotionId}
                          </p>
                          <p className="text-[10px] text-[var(--text-muted)] uppercase tracking-tight">
                            {new Date(entry.date).toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric' })}
                          </p>
                        </div>
                      </div>
                      <div className="text-[10px] font-bold px-2 py-1 bg-white/5 rounded-md text-[var(--text-muted)]">
                        LOGGED
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </div>

          {/* Professional Handover Card */}
          <div className="flex flex-col gap-6">
            <div className="glass-card p-6 border border-[var(--color-primary)]/20 bg-[var(--color-primary)]/5 space-y-4">
              <div className="flex items-center gap-2">
                <FileText className="w-4 h-4 text-[var(--color-primary)]" />
                <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--text-main)]">Doctor Summary</h3>
              </div>
              <p className="text-xs text-[var(--text-muted)] leading-relaxed">
                Walking into a doctor's appointment can be stressful. This tool prepares a summary of your trends to make the conversation easier.
              </p>
              <button
                onClick={handleExportForDoctor}
                className="w-full py-3 bg-[var(--color-primary)] text-black rounded-xl text-xs font-bold hover:scale-[1.02] active:scale-[0.98] transition-all flex items-center justify-center gap-2"
              >
                <Download className="w-4 h-4" />
                Download Summary
              </button>
            </div>

            <div className="flex gap-2 items-start bg-black/10 p-4 rounded-xl border border-[var(--border-subtle)]/60">
              <AlertCircle className="w-4 h-4 text-[var(--text-muted)] flex-shrink-0 mt-0.5" />
              <p className="text-[11px] leading-normal text-[var(--text-muted)]">
                <strong>Privacy:</strong> This report is generated entirely in your browser. No data is sent to our servers or stored anywhere except your device.
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
